name: Blob storage website CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: 🧰 Install dependencies
        run: npm install

      - name: 📦 Build & Export project
        run: npm run build --if-present

      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            az storage blob upload-batch --account-name demostorage3513 -d '$web' -s ./out/

      - name: logout
        run: |
          az logout
